### PR TITLE
Use FirebaseFireStore wisely. 

### PR DESCRIPTION
**Pull request by Subhadiptech**

### CODE REVIEW

**Comment by niharika2810** [comment]
Hey @Subhadiptech Thank you for added more points. It would be really helpful if you could mention the scenarios where we use it and how developers will find it more impactful and significant. Could you please add few examples?

**Comment by Subhadiptech** [comment]
Ofc I will. Thanks for your concern

**Comment by Subhadiptech** [comment]
Can you please review my PR ? @niharika2810

**Review by niharika2810 — APPROVED** [review]

**Comment by niharika2810** [comment]
Hey @Subhadiptech Could you please resolve the conflicts. I will merge this then.

**Comment by Subhadiptech** [comment]
Done @niharika2810

**Comment by niharika2810** [comment]
Thank you :)

**Comment by Subhadiptech** [comment]
@niharika2810  can we add this repo to hactoberfest 2021 xD.

**Comment by niharika2810** [comment]
Hey this is already there.

**Comment by Subhadiptech** [comment]
But On my hacktoberfest profile its indicating that its not included as a hactoberfest repo. Can you please confirm this. @niharika2810

**Comment by Subhadiptech** [comment]
Thanks for your concern :)

**Pull request merged**
