### PR TITLE
Add Information about In-app review API

### PR DESCRIPTION
**Pull request by ELTEGANI**
This new feature will help developers to give users the ability to leave a review from within the app without heading back to the App Details page.

### CODE REVIEW

**Review by niharika2810 — APPROVED** [review]

**Comment by niharika2810** [comment]
Thank you for this new point and raising it. 👍🏻

**Comment by ELTEGANI** [comment]
You are wellcome i will keep PR once i learn new topic.

**Comment by ELTEGANI** [comment]
> Thank you for this new point and raising it. 👍🏻

You are wellcome i will keep PR once i learn new topic.

**Comment by niharika2810** [comment]
Should I add your point to the article too?

**Comment by ELTEGANI** [comment]
> Should I add your point to the article too?

yes for sure

**Comment by ELTEGANI** [comment]
> Should I add your point to the article too?
as you want but I think of you indicate in the awesome article that more will be added to the repo to avoid keep update the article.

**Pull request merged**
